# RPGHealth Configuration
settings:
  base-display-hp: 100
  display-hp-per-level: 5
  base-vanilla-hp: 20
  vanilla-hp-per-level: 0.5
  regen-amount: 0.1
  regen-interval: 60
  base-xp: 200
  xp-scale: 1.3
  respawn-hp-percent: 0.5
